SELECT*
FROM
  BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP
LIMIT
  10;
SELECT*
FROM
  BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE
LIMIT
  10;
  -- Checking for missing values in the tables
SELECT * FROM  BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE
WHERE userid IS NULL OR NAME IS NULL OR surname IS NULL OR email IS NULL OR gender IS NULL OR RACE IS NULL OR AGE IS NULL OR PROVINCE IS NULL OR SOCIAL_MEDIA_HANDLE IS NULL;

 
--Determine total viewership
Select Distinct count(USERID) AS TOTAL_VIEWERSHIP
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP;

--Viewership by province
SELECT U.PROVINCE,
COUNT(U.USERID)AS COUNT_BY_PROVINCE
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE AS U
INNER JOIN BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP AS V
ON U.UserID = V.UserID
GROUP BY 1
ORDER BY COUNT_BY_PROVINCE DESC;



--USER BY RACE
SELECT RACE,
COUNT(U.USERID) AS COUNT_BY_RACE 
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE AS U
INNER JOIN BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP AS V
ON U.UserID = V.UserID
where race is not null
GROUP BY 1
ORDER BY COUNT_BY_RACE DESC;

--USER BY GENDER
SELECT GENDER,
COUNT(U.USERID) AS COUNT_BY_GENDER
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE AS U
INNER JOIN BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP AS V
ON U.UserID = V.UserID
where gender !='None'
GROUP BY GENDER;

--AGE COHORTS
SELECT AGE,
name,
surname,
CASE
WHEN AGE BETWEEN '1' AND '12'THEN 'KIDS'
WHEN AGE BETWEEN '13'AND '19'THEN 'TEEN'
WHEN AGE BETWEEN '20' AND '35'THEN 'YOUTH'
WHEN AGE BETWEEN '36' AND '50'THEN 'ADULTS'
WHEN AGE BETWEEN '51' AND '65'THEN 'MATURED ADULTS'
WHEN AGE >65 THEN  'RETIRED'
ELSE 'Not Specified'
END AS Age_Group
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE;

--HOW many users are watching from social media
SELECT COUNT(SOCIAL_MEDIA_HANDLE)AS TOTAL_SOCIAL_MEDIA_HANDLE,
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE
WHERE SOCIAL_MEDIA_HANDLE !='None';
--HOW many users who dont have social media
SELECT COUNT(SOCIAL_MEDIA_HANDLE)AS NONE_SOCIAL_MEDIA_HANDLE,
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE
WHERE SOCIAL_MEDIA_HANDLE ='None';


-- Convert UTC → South African Time (UTC+2)
CREATE OR REPLACE TABLE BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP AS
SELECT
    USERID,
    CHANNEL2,
    RECORDDATE2,
    DURATION2,
    CONVERT_TIMEZONE('UTC', 'Africa/Johannesburg', TO_TIMESTAMP(RecordDate2, 'YYYY/MM/DD HH24:MI')) AS VIEW_TIME_SA
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP;

--Time buckets
SELECT
    u.userid,
    u.Name,
    u.Surname,
    u.Gender,
    u.Race,
    u.Province,
    u.Age,
    v.channel2,
    v.duration2,
        CASE
        WHEN v.DURATION2 between '00:00:00' AND '03:00:00' THEN '0 to 3 Hrs'
        WHEN v.DURATION2 between '03:00:01' AND '06:00:00' THEN '3 to 6 Hrs'
        WHEN v.DURATION2 between '06:00:01' AND '09:00:00' THEN '6 to 9 Hrs'
        ELSE '9 to 12 Hrs'
    END AS Watch_Duration,
    DAYNAME(v.VIEW_TIME_SA) AS DAY_OF_WEEK,
    TO_TIME(v.VIEW_TIME_SA) AS TIME, 
    DATE_PART(HOUR, v.VIEW_TIME_SA) AS HOUR_OF_DAY,
    CASE
        WHEN v.duration2 BETWEEN '02:00:00' AND '05:59:59' THEN 'Early Morning'
        WHEN v.duration2 between '06:00:00' AND '11:59:59' THEN 'Morning'
        WHEN v.duration2 between '12:00:00' AND '17:59:59' THEN 'Afternoon'
        WHEN v.duration2 between '18:00:00' AND '23:59:59' THEN 'Evening'
        ELSE 'Night'
    END AS Time_Bucket,
    MONTHNAME(v.VIEW_TIME_SA) AS MONTH
FROM BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHT_PROFILE AS u
INNER JOIN BRIGHT_TV.BRIGHT_TV_PROFILE.BRIGHTTV_VIEWERSHIP AS v 
ON u.USERID = v.USERID;


















